"""The security core for xtr applications.

Users, tokens, roles, voters and the authorization decision — everything that
needs no HTTP edge and no JSON Web Tokens. This module gathers the public
surface so an application imports it from one place.
"""

from __future__ import annotations

from .authentication import (
    AuthenticationTrustResolver,
    AuthenticationTrustResolverInterface,
)
from .authentication.token import (
    AbstractToken,
    NullToken,
    TokenInterface,
    UsernamePasswordToken,
)
from .authentication.token.storage import TokenStorage, TokenStorageInterface
from .authorization import (
    Access,
    AccessDecision,
    AccessDecisionManager,
    AccessDecisionManagerInterface,
    AccessDecisionStrategyInterface,
    AffirmativeStrategy,
    AuthenticatedVoter,
    AuthorizationChecker,
    AuthorizationCheckerInterface,
    CacheableVoterInterface,
    ClosureVoter,
    ConsensusStrategy,
    GuestAuthorizationCheckerInterface,
    IsGrantedContext,
    PriorityStrategy,
    RoleHierarchyVoter,
    RoleVoter,
    TraceableVoter,
    UnanimousStrategy,
    Vote,
    Voter,
    VoterInterface,
)
from .event import AuthenticationEvent, AuthenticationSuccessEvent, VoteEvent
from .exception import (
    AccessDeniedError,
    AccountExpiredError,
    AccountStatusError,
    AuthenticationCredentialsNotFoundError,
    AuthenticationError,
    AuthenticationServiceError,
    BadCredentialsError,
    CredentialsExpiredError,
    CustomUserMessageAccountStatusError,
    CustomUserMessageAuthenticationError,
    DisabledError,
    InsufficientAuthenticationError,
    InvalidArgumentError,
    LockedError,
    SecurityError,
    UnsupportedUserError,
    UserNotFoundError,
)
from .role import RoleHierarchy, RoleHierarchyInterface
from .user import (
    AttributesBasedUserProviderInterface,
    ChainUserChecker,
    ChainUserProvider,
    EquatableInterface,
    InMemoryUser,
    InMemoryUserChecker,
    InMemoryUserProvider,
    OidcUser,
    PasswordUpgraderInterface,
    UserCheckerInterface,
    UserInterface,
    UserProviderInterface,
)

__all__ = [
    "AbstractToken",
    "Access",
    "AccessDecision",
    "AccessDecisionManager",
    "AccessDecisionManagerInterface",
    "AccessDecisionStrategyInterface",
    "AccessDeniedError",
    "AccountExpiredError",
    "AccountStatusError",
    "AffirmativeStrategy",
    "AttributesBasedUserProviderInterface",
    "AuthenticatedVoter",
    "AuthenticationCredentialsNotFoundError",
    "AuthenticationError",
    "AuthenticationEvent",
    "AuthenticationServiceError",
    "AuthenticationSuccessEvent",
    "AuthenticationTrustResolver",
    "AuthenticationTrustResolverInterface",
    "AuthorizationChecker",
    "AuthorizationCheckerInterface",
    "BadCredentialsError",
    "CacheableVoterInterface",
    "ChainUserChecker",
    "ChainUserProvider",
    "ClosureVoter",
    "ConsensusStrategy",
    "CredentialsExpiredError",
    "CustomUserMessageAccountStatusError",
    "CustomUserMessageAuthenticationError",
    "DisabledError",
    "EquatableInterface",
    "GuestAuthorizationCheckerInterface",
    "InMemoryUser",
    "InMemoryUserChecker",
    "InMemoryUserProvider",
    "InsufficientAuthenticationError",
    "InvalidArgumentError",
    "IsGrantedContext",
    "LockedError",
    "NullToken",
    "OidcUser",
    "PasswordUpgraderInterface",
    "PriorityStrategy",
    "RoleHierarchy",
    "RoleHierarchyInterface",
    "RoleHierarchyVoter",
    "RoleVoter",
    "SecurityError",
    "TokenInterface",
    "TokenStorage",
    "TokenStorageInterface",
    "TraceableVoter",
    "UnanimousStrategy",
    "UnsupportedUserError",
    "UserCheckerInterface",
    "UserInterface",
    "UserNotFoundError",
    "UserProviderInterface",
    "UsernamePasswordToken",
    "Vote",
    "VoteEvent",
    "Voter",
    "VoterInterface",
]
