[project]
name = "xtr"
version = "1.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv.workspace]
members = ["packages/xtr-*"]

[tool.uv]
package = false

[tool.uv.sources]
xtr-cache                = { workspace = true }
xtr-cache-contracts      = { workspace = true }
xtr-clock                = { workspace = true }
xtr-console              = { workspace = true }
xtr-dependency-injection = { workspace = true }
xtr-dotenv               = { workspace = true }
xtr-lock                 = { workspace = true }
xtr-logging              = { workspace = true }
xtr-logging-contracts    = { workspace = true }
xtr-messenger            = { workspace = true }
xtr-scheduler            = { workspace = true }
xtr-service-contracts    = { workspace = true }

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
